# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kjon-django'
primary_region = 'iad'
console_command = '/code/manage.py shell'

[build]
  ignorefile = ".dockerignore"

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  FLY_APP_NAME = "kjon-django"

[[services]]
  internal_port = 8000
  protocol = "tcp"
  
  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'